$DDAT:==DIR *.DAT
$DOUT:==DIR *.OUT
$DARC:==DIR *.ARC
$DRES:==DIR *.RES
$DDEN:==DIR *.DEN
$ASSIGN [STEWART.WORKSHOP] MOPACDIRECTORY             
$MOPAC  :== @MOPACDIRECTORY:MOPAC          
$SHUT*DOWN  :== RUN MOPACDIRECTORY:SHUTDOWN   
$ASSIGN DBA0:[STEWART.WORKSHOP]MOPAC HLP$LIBRARY   
