$!
$!	Write VAXPORT tape
$!
$    SET VERIFY
$       ALL MTA0:
$	INIT	MTA0:	MOPAC	/DENS=1600
$	MOUNT	MTA0:	MOPAC
$	COPY	/READCHECK *.FOR    	MTA0:
$	COPY	/READCHECK *.COM    	MTA0:
$	COPY	/READCHECK *.OPT    	MTA0:
$	COPY	/READCHECK *.MAN    	MTA0:
$	COPY	/READCHECK *.HLP    	MTA0:
$	COPY	/READCHECK *.DAT   	MTA0:
$	COPY	/READCHECK *.OUT   	MTA0:
$!	DISM	/NOUNLOAD	MTA0:
