
     SUBROUTINE DIAG(FAO,VECTOR,NOCC,EIG,MDIM,N)              
     IMPLICIT DOUBLE PRECISION(A-H,O-Z)                                   
     INCLUDE 'SIZES/NOLIST'
     DIMENSION FAO(*),VECTOR(MDIM,*),EIG(*),WS(MAXORB)          
***********************************************************************
                                                                       
   "FAST" DIAGONALISATION PROCEDURE.                                   
                                                                       
    ON INPUT FAO CONTAINS THE LOWER HALF TRIANGLE OF THE MATRIX TO BE  
                         DIAGONALISED, PACKED.                         
             VECTOR  CONTAINS THE OLD EIGENVECTORS ON INPUT, THE NEW   
             VECTORS ON EXITING.                                       
             NOCC = NUMBER OF OCCUPIED MOLECULAR ORBITALS.             
             EIG  = EIGENVALUES FROM AN EXACT DIAGONALISATION          
             MDIM = DECLARED SIZE OF MATRIX "C".                       
             N = NUMBER OF ATOMIC ORBITALS IN BASIS SET                
                                                                       
  DIAG IS A PSEUDO-DIAGONALISATION PROCEDURE, IN THAT THE VECTORS THAT 
       ARE GENERATED BY IT ARE MORE NEARLY ABLE TO BLOCK-DIAGONALISE   
       THE FOCK MATRIX OVER MOLECULAR ORBITALS THAN THE STARTING       
       VECTORS. IT MUST BE CONSIDERED PSEUDO FOR SEVERAL REASONS:      
       (A) IT DOES NOT GENERATE EIGENVECTORS - THE SECULAR DETERMINANT 
           IS NOT DIAGONALISED, ONLY THE OCCUPIED-VIRTUAL INTERSECTION.
       (B) MANY SMALL ELEMENTS IN THE SEC.DET. ARE IGNORED AS BEING TOO
           SMALL COMPARED WITH THE LARGEST ELEMENT.                    
       (C) WHEN ELEMENTS ARE ELIMINATED BY ROTATION, THE REST OF THE   
           SEC. DET. IS ASSUMED NOT TO CHANGE, I.E. ELEMENTS CREATED   
           ARE IGNORED.                                                
       (D) THE ROTATION REQUIRED TO ELIMINATE THOSE ELEMENTS CONSIDERED
           SIGNIFICANT IS APPROXIMATED TO USING THE EIGENVALUES OF THE 
           EXACT DIAGONALISATION THROUGHOUT THE REST OF THE ITERATIVE  
           PROCEDURE.                                                  
                                                                       
  (NOTE:- IN AN ITERATIVE PROCEDURE ALL THE APPROXIMATIONS PRESENT IN  
          DIAG BECOME VALID AT SELF-CONSISTENCY, SELF-CONSISTENCY IS   
          NOT SLOWED DOWN BY USE OF THESE APPROXIMATIONS)              

    REFERENCE:
             "FAST SEMIEMPIRICAL CALCULATIONS",
             STEWART. J.J.P., CSASZAR, P., PULAY, P., J. COMP. CHEM.,
             3, 227, (1982)
                                                                       
***********************************************************************
     PARAMETER (MDUMY=MAXORB*MAXORB+(NUMATM*(NUMATM+1))/2-MORB2)
     COMMON /SCRACH/ FMO(MORB2), XDUMY(MDUMY)
             FMO  IS A WORK-SPACE OF SIZE (N-NOCC)*NOCC, IT WILL HOLD  
                  THE FOCK MOLECULAR ORBITAL INTERACTION MATRIX.       
                                                                       
  FIRST, CONSTRUCT THAT PART OF A SECULAR DETERMINANT OVER MOLECULAR   
  ORBITALS WHICH CONNECTS THE OCCUPIED AND VIRTUAL SETS.               
                                                                       
***********************************************************************
                                                                       
     TINY=0.D0                                                         
     LUMO=NOCC+1                                                       
     IJ=0                                                              
     DO 6 I=LUMO,N                                                     
       KK=0                                                            
       DO 3 J=1,N                                                      
         SUM=0.D0                                                      
         DO 1 K=1,J                                                    
           KK=KK+1                                                     
  1        SUM=SUM+FAO(KK)*VECTOR(K,I)                                 
         IF(J.EQ.N) GOTO 3                                             
         J1=J+1                                                        
         K2=KK                                                         
         DO 2 K=J1,N                                                   
           K2=K2+K-1                                                   
  2        SUM=SUM+FAO(K2)*VECTOR(K,I)                                 
  3      WS(J)=SUM                                                     
         DO 5 J=1,NOCC                                                 
         IJ=IJ+1                                                       
         SUM=0.D0                                                      
         DO 4 K=1,N                                                    
  4        SUM=SUM+WS(K)*VECTOR(K,J)                                   
         IF(TINY.LT.ABS(SUM)) TINY=ABS(SUM)                            
  5      FMO(IJ)=SUM                                                   
  6    CONTINUE                                                        
     TINY=0.04D0*TINY                                                  
***********************************************************************
                                                                       
   NOW DO A CRUDE 2 BY 2 ROTATION TO "ELIMINATE" SIGNIFICANT ELEMENTS  
                                                                       
***********************************************************************
     IJ=0                                                              
     DO 10 I=LUMO,N                                                    
         DO 9 J=1,NOCC                                                 
         IJ=IJ+1                                                       
         IF(ABS(FMO(IJ)).LT.TINY) GOTO 9                               
                                                                       
      BEGIN 2 X 2 ROTATIONS                                            
                                                                       
         A=EIG(J)                                                      
         B=EIG(I)                                                      
         C=FMO(IJ)                                                     
         D=A-B                                                         
         E=SIGN(SQRT(4.D0*C*C+D*D),D)                                  
         ALPHA=SQRT(0.5D0*(1.D0+D/E))                                  
         BETA=-SIGN(SQRT(0.5D0*(1.D0-D/E)),C)                          
                                                                       
      ROTATION OF PSEUDO-EIGENVECTORS                                  
                                                                       
           DO 8 M=1,N                                                  
           A=VECTOR(M,J)                                               
           B=VECTOR(M,I)                                               
           VECTOR(M,J)=ALPHA*A+BETA*B                                  
           VECTOR(M,I)=ALPHA*B-BETA*A                                  
   8     CONTINUE                                                      
   9   CONTINUE                                                        
  10 CONTINUE                                                          
     RETURN                                                            
     END                                                               