      FUNCTION SECOND()
      DOUBLE PRECISION SECOND
C******************************************************
C
C   SECOND, ON EXIT, CONTAINS THE NUMBER OF CPU SECONDS
C   SINCE THE START OF THE CALCULATION.
C
C******************************************************
      LOGICAL FIRST, SET, SETOK
      DATA FIRST, SETOK   /  2 * .TRUE.    /
      IF(FIRST) THEN
          FIRST=.FALSE.
          CALL DEFINE_EVENT_FLAG_CLUSTER
      ENDIF
      CALL TIMCLK(CPU)
      CALL CHECK_EVENT_FLAG(64,SET)
      IF(SET)   THEN
      CPU=CPU+1.D6
      IF( SETOK) THEN
      WRITE(6,'(///10X,''****   JOB STOPPED BY OPERATOR   ****'')')
      SETOK=.FALSE.
      ENDIF
      ENDIF
C TIMCLK IS MACHINE-DEPENDENT. IF YOU DO NOT KNOW THE LOCAL CALL THEN
C INSERT INSTEAD OF THIS LINE "      CPU=CPU+0.1D0"
      SECOND=CPU
      RETURN
      END
