      SUBROUTINE FORCE
      WRITE(6,'(//10X,''OPTION FORCE HAS BEEN USED, BUT SUBROUTINE'',/
     +10X,''FORCE HAS NOT BEEN INCLUDED. EITHER INCLUDE THE MISSING'',/
     +10X,''SUBROUTINES FORCE, FMAT, AXIS, THERMO AND FREQCY AND'',/
     +10X,'' RE-LINK, OR DO NOT USE THE KEY-WORD "FORCE"'')')
      STOP
      END
      SUBROUTINE NLLSQ
      WRITE(6,'(//10X,''OPTION NLLSQ HAS BEEN USED, BUT SUBROUTINE'',/
     +10X,''NLLSQ HAS NOT BEEN INCLUDED. EITHER INCLUDE THE MISSING'',/
     +10X,''SUBROUTINES NLLSQ, PARSAV AND SEARCH AND RE-LINK, OR'',/
     +10X,''DO NOT USE THE KEY-WORD "FORCE" OR "NLLSQ"'')')
      STOP
      END
      SUBROUTINE POWSQ
      WRITE(6,'(//10X,''OPTION SIGMA HAS BEEN USED, BUT SUBROUTINE'',/
     +10X,''POWSQ HAS NOT BEEN INCLUDED. EITHER INCLUDE THE MISSING'',/
     +10X,''SUBROUTINES POWSQ AND POWSAV AND RE-LINK, OR'',/
     +10X,''DO NOT USE THE KEY-WORD "SIGMA"'')')
      STOP
      END
